#!/bin/bash
# Setup on a debian type machine

virtualenv --no-site-packages venv
source venv/bin/activate

sudo apt-get install redis-server postgresql nginx
pip install -r requirements
python worldofloot/autocomplete/autocomplete.py create
