from django.conf.urls import patterns, url
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('worldofloot.main.views',
    url(r'^$', 'index', name='index'),
    url(r'^about/', 'about', name='about'),
    url(r'^my/', 'my_loot', name='my_loot'),
    url(r'^api/my_loot/(\d+)', 'my_loot_json', name='my_loot_json'),
    url(r'^recent/$', 'recent', name='recent'),
    url(r'^recent/(\d+)', 'recent', name='recent'),
    url(r'^api/recent/(\d+)', 'recent_json', name='recent_json'),
    url(r'^popular/$', 'popular', name='popular'),
    url(r'^popular/(\d+)', 'popular', name='popular'),
    url(r'^api/popular/(\d+)', 'popular_json', name='popular_json'),
    url(r'^user/(.*)', 'user', name='user'),
    url(r'^api/user_loot/([^/]+)/(\d+)', 'user_loot_json', name='user_loot_json'),
    url(r'^info/(.*)/(.*)', 'get_item_info', name='get_item_info'),
    url(r'^add/(.*)/(.*)/(.*)', 'add_item', name='add_item'),
    url(r'^remove/(.*)/(.*)', 'remove_item', name='remove_item'),
    url(r'^turn_off_welcome_banner/', 'turn_off_welcome_banner', name='turn_off_welcome_banner'),
    url(r'^login_or_create/', 'login_or_create', name='login_or_create'),
    url(r'^logout/', 'logout_user', name='logout_user'),
    url(r'^robots\.txt$', direct_to_template,
         {'template': 'robots.txt', 'mimetype': 'text/plain'}),
)
